version: 2
updates:
  - package-ecosystem: 'npm'
    open-pull-requests-limit: 10
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'acdibble'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      types:
        patterns:
          - '@types/*'
